// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	IDUser    uuid.UUID
	Name      string
	LastName  string
	Email     string
	CreatedAt sql.NullTime
}
