CREATE TABLE IF NOT EXISTS users (
    id_user  UUID NOT NULL PRIMARY KEY,
	name TEXT NOT NULL,
    last_name TEXT NOT NULL,
	email TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);