// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name     string `json:"Name"`
	LastName string `json:"LastName"`
	Email    string `json:"Email"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"Name"`
	LastName string `json:"LastName"`
	Email    string `json:"Email"`
}
