name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20  # Modifique para a versão 1.20 do Go ou a versão desejada

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...