name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: ci-golang-workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Build
      run: go build -a -installsuffix cgo -o app ./cmd/app
    - name: Test
      run: go test -coverpkg=./... -coverprofile coverage.out -v ./...  
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}